config/routes.rb
Lunch::Application.routes.draw do
  
  root :to => 'employees#overview'
	
  resources :employees do
    get :overview, :on => :collection
    get :overview_per_month, :on => :member
    get :register_lunch, :on => :member
    put :create_lunch, :on => :member
  end
  
  resources :given_lunches do
    get :overview, :on => :collection
  end
  
  resources :lunch_lists, :given_lunches, :employees

  get "pages/home"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :employee_id
  attr_accessible :lastname_dutch
  
  has_many :lunch_lists
  has_many :given_lunches, :through => :lunch_lists

  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates :employee_id, :presence => true
  validates_length_of :employee_id, :is => 5
  validates_uniqueness_of :employee_id
    
  default_scope :order => 'lastname ASC'
  
  def full_name
    "#{lastname}, #{firstname}"
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.xml
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.xml
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.xml
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.xml
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to(@employee, :notice => 'Employee was successfully created.') }
        format.xml  { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.xml
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to(@employee, :notice => 'Employee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.xml
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to(employees_url) }
      format.xml  { head :ok }
    end
  end
  
  def overview
    @employees = Employee.all
    @employees_by_lastname = @employees.group_by { |t| t.lastname[0] }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end
  
  def register_lunch
    @employee = Employee.find(params[:id])   
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employee }
    end
  end
  
  def create_lunch
   params[:lunch_ids].each do |new_lunch| 
       lunch = LunchList.new 
       lunch.employee_id = params[:id]
       lunch.given_lunch_id = new_lunch
       lunch.save 
    end
  
    flash[:notice] = 'Lunches were successfully updated.'
    redirect_to :action => "overview"  
  end  
  
  def overview_per_month
    @employee = Employee.find(params[:id])
    @lunches_per_month = Employee.find(params[:id]).given_lunches.group_by { |lunch| lunch.date_of_lunch.strftime("%B") }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lunches_per_month }
    end
  end
  
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Employee ID</th>
    <th></th>
    <th></th>
	<th></th>
	<th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.firstname %></td>
    <td><%= employee.lastname %></td>
    <td><%= employee.employee_id %></td>
    <td><%= link_to 'Month view', overview_per_month_employee_path(employee) %></td>
	<td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/overview.html.erb
<p id="notice"><%= notice %></p>

<% @employees_by_lastname.keys.sort.each do |letter| %>  
<ul id="employees">
  <% for employee in @employees_by_lastname[letter] %>  
    <li>
		<%= link_to "#{employee.full_name}", register_lunch_employee_path(employee) %>
	</li>
  <% end %>  
<% end %>
	<br />
	<% #link_to '(maandstaat)', overview_per_month_employee_path(employee) %>
	

app/views/employees/overview_per_month.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @employee.full_name %></h1>
<table>
<% @lunches_per_month.each do |month, lunches| %>
	<tr><td><h2><%= month %></h2></td></tr>
  	<tr>
	    <th>Date of lunch</th>
	    <th>Price</th>    
	  </tr>
	<% lunches.each do |given_lunch| %>
	  <tr>
	    <td><%= given_lunch.date_of_lunch.strftime("%A, %e %B") %></td>
	    <td><%= given_lunch.price %></td>
	  </tr>
	<% end %>
	<tr><td>This month: <%= lunches.length %> lunches</td></tr>
<% end %>
</table>

app/views/employees/register_lunch.html.erb
<% @lunch = GivenLunch.today %>
<% @lunch_today = @lunch.first unless @lunch.empty? %>
<% notice = "Geen lunch bekend voor vandaag." %>

<h1>Hoi <%= @employee.firstname %>!</h1>
<p>Selecteer lunch om te registreren:</p>

<% if @lunch.empty? %>
	<p id="notice"><%= notice %></p>
<% else %>
	<% form_tag create_lunch_employee_path, :method => :put do %>
		<ul id="display-inline-block">
			<li class="today">
			<strong><%= @lunch_today.date_of_lunch.strftime("%A")  %></strong>
			<br />
			<%= @lunch_today.date_of_lunch.strftime("%e %B, %G")  %>
			<br /><br />
			<div style="text-align: center;"><%= check_box_tag "lunch_ids[]", @lunch_today.id  %></div>
			</li>
		</ul>
		<p><%= submit_tag "Bewaar lunch" %></p>
	<% end %>
<% end %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @employee.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @employee.lastname %>
</p>

<p>
  <b>Employee id:</b>
  <%= @employee.employee_id %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>