config/routes.rb
Lunch::Application.routes.draw do
  
  root :to => 'employees#overview'
	
  resources :employees do
    get :overview, :on => :collection
    get :overview_per_month, :on => :member
    get :register_lunch, :on => :member
    put :create_lunch, :on => :member
  end
  
  resources :given_lunches do
    get :overview, :on => :collection
  end
  
  resources :lunch_lists, :given_lunches, :employees

  get "pages/home"

end

app/models/lunch_list.rb
class LunchList < ActiveRecord::Base
  belongs_to :employee
  belongs_to :given_lunch
  
  validates :employee_id, :presence => true
  validates :given_lunch, :presence => true
  
  validates_uniqueness_of :given_lunch_id, :scope => :employee_id, :message => "- has already been associated with this employee" 
  
  
  
end

app/controllers/lunch_lists_controller.rb
class LunchListsController < ApplicationController
  # GET /lunch_lists
  # GET /lunch_lists.xml
  def index
    @lunch_lists = LunchList.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lunch_lists }
    end
  end

  # GET /lunch_lists/1
  # GET /lunch_lists/1.xml
  def show
    @lunch_list = LunchList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lunch_list }
    end
  end

  # GET /lunch_lists/new
  # GET /lunch_lists/new.xml
  def new
    @lunch_list = LunchList.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lunch_list }
    end
  end

  # GET /lunch_lists/1/edit
  def edit
    @lunch_list = LunchList.find(params[:id])
  end

  # POST /lunch_lists
  # POST /lunch_lists.xml
  def create
    @lunch_list = LunchList.new(params[:lunch_list])

    respond_to do |format|
      if @lunch_list.save
        format.html { redirect_to(@lunch_list, :notice => 'Lunch list was successfully created.') }
        format.xml  { render :xml => @lunch_list, :status => :created, :location => @lunch_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lunch_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lunch_lists/1
  # PUT /lunch_lists/1.xml
  def update
    @lunch_list = LunchList.find(params[:id])

    respond_to do |format|
      if @lunch_list.update_attributes(params[:lunch_list])
        format.html { redirect_to(@lunch_list, :notice => 'Lunch list was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lunch_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lunch_lists/1
  # DELETE /lunch_lists/1.xml
  def destroy
    @lunch_list = LunchList.find(params[:id])
    @lunch_list.destroy

    respond_to do |format|
      format.html { redirect_to(lunch_lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lunch_lists_helper.rb
module LunchListsHelper
end

app/views/lunch_lists/_form.html.erb
<% # get employees and lunch dates %>
<% @employees = Employee.all %>
<% @given_lunches = GivenLunch.all %>

<%= form_for(@lunch_list) do |f| %>
  <% if @lunch_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch_list.errors.count, "error") %> prohibited this lunch_list from being saved:</h2>

      <ul>
      <% @lunch_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :employee_id %><br />
	<%= f.collection_select :employee_id, @employees, :id, :fullname, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :givenlunch_id %><br />
	<%= f.collection_select :given_lunch_id, @given_lunches, :id, :date_of_lunch, :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunch_lists/edit.html.erb
<h1>Editing lunch_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch_list %> |
<%= link_to 'Back', lunch_lists_path %>

app/views/lunch_lists/index.html.erb
<h1>All Employees</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Given lunches</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lunch_lists.each do |lunch_list| %>
  <tr>
    <td><%= lunch_list.employee_id %></td>
    <td><%= lunch_list.given_lunch_id %></td>
    <td><%= link_to 'Show', lunch_list %></td>
    <td><%= link_to 'Edit', edit_lunch_list_path(lunch_list) %></td>
    <td><%= link_to 'Destroy', lunch_list, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lunch list', new_lunch_list_path %>

app/views/lunch_lists/new.html.erb
<h1>New lunch_list</h1>

<%= render 'form' %>

<%= link_to 'Back', lunch_lists_path %>

app/views/lunch_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @lunch_list.employee_id %>
</p>

<p>
  <b>Given lunches:</b>
  <%= @lunch_list.given_lunch_id %>
</p>


<%= link_to 'Edit', edit_lunch_list_path(@lunch_list) %> |
<%= link_to 'Back', lunch_lists_path %>