config/routes.rb
Lunch::Application.routes.draw do
  
  root :to => 'employees#overview'
	
  resources :employees do
    get :overview, :on => :collection
    get :overview_per_month, :on => :member
    get :register_lunch, :on => :member
    put :create_lunch, :on => :member
  end
  
  resources :given_lunches do
    get :overview, :on => :collection
  end
  
  resources :lunch_lists, :given_lunches, :employees

  get "pages/home"

end

app/models/given_lunch.rb
class GivenLunch < ActiveRecord::Base
  has_many :lunch_lists, :dependent => :destroy
  has_many :employees, :through => :lunch_lists
  
  validates :date_of_lunch, :presence => true
  validates :price, :presence => true
  validates_uniqueness_of :date_of_lunch 
  
  default_scope :order => 'date_of_lunch ASC'
  
  # get the days of the current week
  today = Time.new.strftime("%F")
  
  scope :today, where("date_of_lunch = ? ", today)
  
end

app/controllers/given_lunches_controller.rb
class GivenLunchesController < ApplicationController
  # GET /given_lunches
  # GET /given_lunches.xml
  def index
    @given_lunches = GivenLunch.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @given_lunches }
    end
  end

  # GET /given_lunches/1
  # GET /given_lunches/1.xml
  def show
    @given_lunch = GivenLunch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @given_lunch }
    end
  end

  # GET /given_lunches/new
  # GET /given_lunches/new.xml
  def new
    @given_lunch = GivenLunch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @given_lunch }
    end
  end

  # GET /given_lunches/1/edit
  def edit
    @given_lunch = GivenLunch.find(params[:id])
  end

  # POST /given_lunches
  # POST /given_lunches.xml
  def create
    @given_lunch = GivenLunch.new(params[:given_lunch])

    respond_to do |format|
      if @given_lunch.save
        format.html { redirect_to(@given_lunch, :notice => 'Given lunch was successfully created.') }
        format.xml  { render :xml => @given_lunch, :status => :created, :location => @given_lunch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @given_lunch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /given_lunches/1
  # PUT /given_lunches/1.xml
  def update
    @given_lunch = GivenLunch.find(params[:id])

    respond_to do |format|
      if @given_lunch.update_attributes(params[:given_lunch])
        format.html { redirect_to(@given_lunch, :notice => 'Given lunch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @given_lunch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /given_lunches/1
  # DELETE /given_lunches/1.xml
  def destroy
    @given_lunch = GivenLunch.find(params[:id])
    @given_lunch.destroy

    respond_to do |format|
      format.html { redirect_to(given_lunches_url) }
      format.xml  { head :ok }
    end
  end
  
  def overview
      # Group lunch dates by month
      @given_lunch_months = GivenLunch.all.group_by { |lunch| lunch.date_of_lunch.strftime("%B") }
  end
  
end

app/helpers/given_lunches_helper.rb
module GivenLunchesHelper
end

app/views/given_lunches/_form.html.erb
<%= form_for(@given_lunch) do |f| %>
  <% if @given_lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@given_lunch.errors.count, "error") %> prohibited this given_lunch from being saved:</h2>

      <ul>
      <% @given_lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_lunch %><br />
	<div class="turn-me-into-datepicker"></div>
  	<%= f.hidden_field 'date_of_lunch' %>	
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/given_lunches/edit.html.erb
<h1>Editing given_lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @given_lunch %> |
<%= link_to 'Back', given_lunches_path %>

app/views/given_lunches/index.html.erb
<h1>Listing given_lunches</h1>

<table>
  <tr>
    <th>Date of lunch</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @given_lunches.each do |given_lunch| %>
  <tr>
    <td><%= given_lunch.date_of_lunch %></td>
    <td><%= given_lunch.price %></td>
    <td><%= link_to 'Show', given_lunch %></td>
    <td><%= link_to 'Edit', edit_given_lunch_path(given_lunch) %></td>
    <td><%= link_to 'Destroy', given_lunch, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Given lunch', new_given_lunch_path %>

			

app/views/given_lunches/new.html.erb
<h1>New given_lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', given_lunches_path %>

app/views/given_lunches/overview.html.erb
<h1>Overview given_lunches</h1>

<table>


<% @given_lunch_months.each do |month, lunches| %>
	<tr><td><h2><%= month %></h2></td></tr>
  	<tr>
	    <th>Date of lunch</th>
	    <th>Price</th>
		<th>Amount of Employees</th>
	    
	  </tr>
	<% lunches.each do |given_lunch| %>
	  <tr>
	    <td><%= given_lunch.date_of_lunch.strftime("%A, %e %B") %></td>
	    <td><%= given_lunch.price %></td>
		<td><%= given_lunch.employees.length %>
	  </tr>
	<% end %>
	<tr><td>Total this month: <%= lunches.length %></td></tr>
<% end %>
</table>

app/views/given_lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date of lunch:</b>
  <%= @given_lunch.date_of_lunch %>
</p>

<p>
  <b>Price:</b>
  <%= @given_lunch.price %>
</p>


<%= link_to 'Edit', edit_given_lunch_path(@given_lunch) %> |
<%= link_to 'Back', given_lunches_path %>